
// This file contains the Base64 encoded data for the Cairo font.
// It is used by jsPDF to render Arabic characters in the generated PDFs.

export const cairoFont = `AAEAAAARAQAABAAQRFNJRwAAAAAAAQAAAAIAAAGQAAAAbEdQOSq2o4gAAUgAAAJgU1VCMmgE+dIAA3fEAAAIrE9TLzJ2+GzBAAABIAAAAGBWFE1YicMAZgAABVgAAAJ2R01YTW1PDQYAABeMAAAAg0dERUYAEAAmAAAYNAAAACBHSURWAAgAKQAAGOgAAABeT1MvMnf4bMEAAP//AAAAYFRhYmxlV3d3d0MAAAAAAAwAAAAAAFNJR1YAIgA3AAAAAQAAARwAAAEAAAAAAAAAAAAAAAIAAAADAAAAFAADAAEAAAAUAAQBTgAAACgA(many more lines of font data)
`;
